Search text of unsupported element without section
At the moment we don't know how to handle this error:
```
Error: Test hook "before" at dist/test_autoyast_unsupported.js:281:28 generated asynchronous activity after the test ended. This activity created the error "ProtocolError: Protocol error (script.callFunction): no such handle Unable to find an object reference for "handle" 30b6ba39-faa4-4801-a8a2-5e1cdddf72fe RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5
NoSuchHandleError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:608:5
deserialize@chrome://remote/content/webdriver-bidi/RemoteValue.sys.mjs:287:13
```
So we revert back to original code for now.